// Generated list of the page text that can be edited in /admin (Page text tab).
// Each entry matches a copy("id", "text") call in a page. Text here is the original wording.
export type CopySlot = { id: string; group: string; text: string };

export const copySlots: CopySlot[] = [
  { id: "faq-kicker", group: "FAQs", text: "FAQs" },
  { id: "faq-title", group: "FAQs", text: "Questions, answered." },
  {
    id: "faq-lede",
    group: "FAQs",
    text: "The things people ask us most. If yours isn’t here, we’d love to hear from you.",
  },
  { id: "home-faq-kicker", group: "Home", text: "FAQs" },
  { id: "home-faq-title", group: "Home", text: "Questions people ask us." },
  {
    id: "home-hero-kicker",
    group: "Home",
    text: "Sustainable infrastructure · Community · Opportunity",
  },
  { id: "home-kicker-1", group: "Home", text: "Our approach" },
  {
    id: "home-h2-1",
    group: "Home",
    text: "Infrastructure should do more than stand. It should create opportunity.",
  },
  { id: "home-kicker-2", group: "Home", text: "What we do" },
  { id: "home-h2-2", group: "Home", text: "Four ways we show up." },
  { id: "home-kicker-3", group: "Home", text: "Impact that can be seen" },
  { id: "home-h2-3", group: "Home", text: "Numbers we will still be proud of in ten years." },
  { id: "home-kicker-4", group: "Home", text: "Featured projects" },
  { id: "home-h2-4", group: "Home", text: "From ideas to places people can use." },
  { id: "home-h2-5", group: "Home", text: "Community at the heart of everything." },
  {
    id: "home-p-1",
    group: "Home",
    text: "Programmes, volunteering, youth, women, skills and local enterprise. The building is never the whole story; the people who will run it write the brief.",
  },
  { id: "home-kicker-5", group: "Home", text: "Upcoming events" },
  { id: "home-h2-6", group: "Home", text: "Rooms you can walk into." },
  { id: "home-kicker-6", group: "Home", text: "Careers" },
  { id: "home-h2-7", group: "Home", text: "Build your career. Build a better future." },
  {
    id: "home-p-2",
    group: "Home",
    text: "Engineering · Project management · Community · and more. Paid roles, apprenticeships and volunteering, all of it real work.",
  },
  { id: "home-h2-8", group: "Home", text: "Field notes from the work." },
  { id: "about-hero-kicker", group: "About", text: "About the trust" },
  { id: "about-hero-title", group: "About", text: "A charity that builds, and stays." },
  { id: "about-kicker-1", group: "About", text: "Who we are" },
  {
    id: "about-h2-1",
    group: "About",
    text: "Connect eVibe exists to make infrastructure do more than stand.",
  },
  {
    id: "about-p-1",
    group: "About",
    text: "Too many places get a building and lose the plot. We were set up so communities can specify, deliver and then own the civic infrastructure they need, homes that hold heat, streets that hold water, rooms that hold people.",
  },
  {
    id: "about-p-2",
    group: "About",
    text: "We work as a trust: independent, charitable, and stubborn about social value. Partners bring land, capital and expertise. Residents bring the brief. We hold the space between them until the work belongs locally.",
  },
  { id: "about-kicker-2", group: "About", text: "How we work" },
  { id: "about-h2-2", group: "About", text: "Connect · Build · Empower, then hand it over." },
  { id: "about-kicker-3", group: "About", text: "Governance" },
  { id: "about-h2-3", group: "About", text: "Incorporated trustees, public duty." },
  {
    id: "about-p-3",
    group: "About",
    text: "The trust is governed by incorporated trustees. We report as a charity in England and Wales, publish impact in plain language, and treat social value as a design requirement, not a paragraph in a tender.",
  },
  { id: "about-dt-1", group: "About", text: "Registered name" },
  { id: "about-dt-2", group: "About", text: "Status" },
  { id: "about-kicker-4", group: "About", text: "What we hold to" },
  { id: "about-h2-4", group: "About", text: "Values we hire against." },
  { id: "what-we-do-hero-kicker", group: "What we do", text: "What we do" },
  { id: "what-we-do-hero-title", group: "What we do", text: "Build. Connect. Empower. Sustain." },
  {
    id: "what-we-do-hero-lede",
    group: "What we do",
    text: "Four practices, one trust. Sustainable infrastructure, community assets, social development and measurable social value.",
  },
  { id: "what-we-do-kicker-1", group: "What we do", text: "From brief to belonging" },
  { id: "what-we-do-h2-1", group: "What we do", text: "A simple sequence. Held carefully." },
  { id: "community-hero-kicker", group: "Community", text: "Community" },
  { id: "community-hero-title", group: "Community", text: "More than a programme page." },
  {
    id: "community-hero-lede",
    group: "Community",
    text: "Initiatives, volunteering, local partnerships, youth, skills and the stories that prove the work is human.",
  },
  { id: "community-kicker-1", group: "Community", text: "Programmes" },
  { id: "community-h2-1", group: "Community", text: "People places prosperity, in that order." },
  { id: "community-kicker-2", group: "Community", text: "Volunteering" },
  { id: "community-h2-2", group: "Community", text: "A few hours that compound." },
  {
    id: "community-p-1",
    group: "Community",
    text: "Open days, planting, mentoring, events. We train, we feed you, we do not waste your time. Under-18s are welcome with an accompanying adult on family days.",
  },
  { id: "community-kicker-3", group: "Community", text: "Partnerships" },
  {
    id: "community-h2-3",
    group: "Community",
    text: "Local authorities, housing providers, colleges, clinics, and the group that already meets in the hall.",
  },
  {
    id: "community-p-2",
    group: "Community",
    text: "We do not land in a neighbourhood and invent a network. We join the one that exists, then add capital, design and delivery muscle. If you are already doing the work, we would rather sit beside you than in front of you.",
  },
  { id: "community-kicker-4", group: "Community", text: "Community stories" },
  {
    id: "community-h2-4",
    group: "Community",
    text: "What it felt like, not just what we counted.",
  },
  { id: "projects-hero-kicker", group: "Projects", text: "Projects" },
  { id: "projects-hero-title", group: "Projects", text: "From ideas to places people can use." },
  {
    id: "projects-hero-lede",
    group: "Projects",
    text: "Retrofit, civic buildings, green infrastructure and neighbourhoods still on the drawing board, all of them specified with the people who will live there.",
  },
  { id: "projects-kicker-1", group: "Projects", text: "Portfolio" },
  { id: "projects-h2-1", group: "Projects", text: "Four places. One way of working." },
  { id: "events-hero-kicker", group: "Events", text: "Events" },
  { id: "events-hero-title", group: "Events", text: "A calendar you can actually use." },
  {
    id: "events-hero-lede",
    group: "Events",
    text: "Workshops, training, fundraising, conferences, project launches, and the days we look back on.",
  },
  { id: "events-kicker-1", group: "Events", text: "Upcoming" },
  { id: "events-h2-1", group: "Events", text: "Come as you are." },
  {
    id: "events-p-1",
    group: "Events",
    text: "Nothing in this category just now. Try another filter.",
  },
  { id: "events-kicker-2", group: "Events", text: "Past events" },
  { id: "events-h2-2", group: "Events", text: "Days that already happened, with pictures." },
  { id: "impact-hero-kicker", group: "Impact", text: "Impact" },
  { id: "impact-hero-title", group: "Impact", text: "Impact that can be seen." },
  {
    id: "impact-hero-lede",
    group: "Impact",
    text: "Communities reached, projects delivered, people engaged, social value created, counted in public.",
  },
  { id: "impact-kicker-1", group: "Impact", text: "How we count" },
  {
    id: "impact-h2-1",
    group: "Impact",
    text: "Social value is a design requirement, not a report at the end.",
  },
  { id: "impact-kicker-2", group: "Impact", text: "This year" },
  { id: "impact-h2-2", group: "Impact", text: "A snapshot, not a victory lap." },
  { id: "impact-kicker-3", group: "Impact", text: "Places behind the numbers" },
  { id: "careers-hero-kicker", group: "Careers", text: "Careers" },
  {
    id: "careers-hero-title",
    group: "Careers",
    text: "Build your career while building stronger communities.",
  },
  {
    id: "careers-hero-lede",
    group: "Careers",
    text: "Not just vacancies. Employed roles, apprenticeships, volunteering, and a culture we will actually describe.",
  },
  { id: "careers-kicker-1", group: "Careers", text: "Working at Connect eVibe" },
  { id: "careers-h2-1", group: "Careers", text: "Kind, not soft. On site, not only on slides." },
  { id: "careers-kicker-2", group: "Careers", text: "Opportunities" },
  { id: "careers-h2-2", group: "Careers", text: "Open seats, including the ones you grow into." },
  { id: "contact-hero-kicker", group: "Contact", text: "Contact" },
  { id: "contact-hero-title", group: "Contact", text: "Six doors. One team." },
  {
    id: "contact-hero-lede",
    group: "Contact",
    text: "Partner, support a project, volunteer, bring a community brief, ask about a career, or just say hello.",
  },
  { id: "contact-p-1", group: "Contact", text: "Also" },
  { id: "get-involved-hero-kicker", group: "Get involved", text: "Get involved" },
  {
    id: "get-involved-hero-title",
    group: "Get involved",
    text: "There is a door for every kind of yes.",
  },
  {
    id: "get-involved-hero-lede",
    group: "Get involved",
    text: "Partner, fund, volunteer, bring a project, start a career, or simply come to the next open day.",
  },
  { id: "get-involved-kicker-1", group: "Get involved", text: "Choose a door" },
  {
    id: "get-involved-h2-1",
    group: "Get involved",
    text: "Real solutions. Lasting impact. You in the room.",
  },
  { id: "get-involved-kicker-2", group: "Get involved", text: "Volunteer roles" },
  {
    id: "get-involved-h2-2",
    group: "Get involved",
    text: "The work is physical, social, and occasionally muddy.",
  },
];
